variable "vm-count" {}
variable "resource_group_location" {}
variable "resource_group_name" {}
variable "common_tags" {}
variable "lb_name" {}
variable "nic_ids" {}
variable "LB_Sku" {}
variable "depend_on_linux_avs" {}
variable "depend_on_vmlinux_1957" {}
